CREATE TABLE IF NOT EXISTS accounts (
    id SERIAL PRIMARY KEY,
    address TEXT NOT NULL UNIQUE,
    blockchain TEXT NOT NULL,
    user_id INTEGER NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

