version: "3.9"
services:
  accounts:
    build:
      context: .
      dockerfile: accounts/Dockerfile
    ports:
      - "${ACCOUNTS_PORT}:${ACCOUNTS_PORT}"
    environment:
      - PORT=${ACCOUNTS_PORT}
    env_file:
      - .env
    depends_on:
      - postgres

  users:
    build:
      context: .
      dockerfile: users/Dockerfile
    ports:
      - "${USERS_PORT}:${USERS_PORT}"
    environment:
      - PORT=${USERS_PORT}
    env_file:
      - .env
    depends_on:
      - postgres

  gateway:
    build:
      context: .
      dockerfile: gateway/Dockerfile
    ports:
      - "${GATEWAY_PORT}:${GATEWAY_PORT}"
    depends_on:
      - accounts
      - users
    environment:
      - PORT=${GATEWAY_PORT}
      - ACCOUNTS_GRPC=accounts:${ACCOUNTS_PORT}
      - USERS_GRPC=users:${USERS_PORT}
    env_file:
      - .env

  postgres:
    image: postgres:15
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: accounts_db
      POSTGRES_USER: accounts_user
      POSTGRES_PASSWORD: accounts_pass

volumes:
  postgres_data:
