// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: balances/balances.proto

package balancespb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UpdateBalancesRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	AccountAddress string                 `protobuf:"bytes,1,opt,name=account_address,json=accountAddress,proto3" json:"account_address,omitempty"`
	Blockchain     string                 `protobuf:"bytes,2,opt,name=blockchain,proto3" json:"blockchain,omitempty"`
	TokenAddress   string                 `protobuf:"bytes,3,opt,name=token_address,json=tokenAddress,proto3" json:"token_address,omitempty"`
	Amount         int64                  `protobuf:"varint,4,opt,name=amount,proto3" json:"amount,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *UpdateBalancesRequest) Reset() {
	*x = UpdateBalancesRequest{}
	mi := &file_balances_balances_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateBalancesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateBalancesRequest) ProtoMessage() {}

func (x *UpdateBalancesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_balances_balances_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateBalancesRequest.ProtoReflect.Descriptor instead.
func (*UpdateBalancesRequest) Descriptor() ([]byte, []int) {
	return file_balances_balances_proto_rawDescGZIP(), []int{0}
}

func (x *UpdateBalancesRequest) GetAccountAddress() string {
	if x != nil {
		return x.AccountAddress
	}
	return ""
}

func (x *UpdateBalancesRequest) GetBlockchain() string {
	if x != nil {
		return x.Blockchain
	}
	return ""
}

func (x *UpdateBalancesRequest) GetTokenAddress() string {
	if x != nil {
		return x.TokenAddress
	}
	return ""
}

func (x *UpdateBalancesRequest) GetAmount() int64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

type UpdateBalancesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateBalancesResponse) Reset() {
	*x = UpdateBalancesResponse{}
	mi := &file_balances_balances_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateBalancesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateBalancesResponse) ProtoMessage() {}

func (x *UpdateBalancesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_balances_balances_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateBalancesResponse.ProtoReflect.Descriptor instead.
func (*UpdateBalancesResponse) Descriptor() ([]byte, []int) {
	return file_balances_balances_proto_rawDescGZIP(), []int{1}
}

func (x *UpdateBalancesResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

var File_balances_balances_proto protoreflect.FileDescriptor

const file_balances_balances_proto_rawDesc = "" +
	"\n" +
	"\x17balances/balances.proto\x12\bbalances\"\x9d\x01\n" +
	"\x15UpdateBalancesRequest\x12'\n" +
	"\x0faccount_address\x18\x01 \x01(\tR\x0eaccountAddress\x12\x1e\n" +
	"\n" +
	"blockchain\x18\x02 \x01(\tR\n" +
	"blockchain\x12#\n" +
	"\rtoken_address\x18\x03 \x01(\tR\ftokenAddress\x12\x16\n" +
	"\x06amount\x18\x04 \x01(\x03R\x06amount\"2\n" +
	"\x16UpdateBalancesResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess2f\n" +
	"\x0fBalancesService\x12S\n" +
	"\x0eUpdateBalances\x12\x1f.balances.UpdateBalancesRequest\x1a .balances.UpdateBalancesResponseB3Z1github.com/block-lytics/proto/balances;balancespbb\x06proto3"

var (
	file_balances_balances_proto_rawDescOnce sync.Once
	file_balances_balances_proto_rawDescData []byte
)

func file_balances_balances_proto_rawDescGZIP() []byte {
	file_balances_balances_proto_rawDescOnce.Do(func() {
		file_balances_balances_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_balances_balances_proto_rawDesc), len(file_balances_balances_proto_rawDesc)))
	})
	return file_balances_balances_proto_rawDescData
}

var file_balances_balances_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_balances_balances_proto_goTypes = []any{
	(*UpdateBalancesRequest)(nil),  // 0: balances.UpdateBalancesRequest
	(*UpdateBalancesResponse)(nil), // 1: balances.UpdateBalancesResponse
}
var file_balances_balances_proto_depIdxs = []int32{
	0, // 0: balances.BalancesService.UpdateBalances:input_type -> balances.UpdateBalancesRequest
	1, // 1: balances.BalancesService.UpdateBalances:output_type -> balances.UpdateBalancesResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_balances_balances_proto_init() }
func file_balances_balances_proto_init() {
	if File_balances_balances_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_balances_balances_proto_rawDesc), len(file_balances_balances_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_balances_balances_proto_goTypes,
		DependencyIndexes: file_balances_balances_proto_depIdxs,
		MessageInfos:      file_balances_balances_proto_msgTypes,
	}.Build()
	File_balances_balances_proto = out.File
	file_balances_balances_proto_goTypes = nil
	file_balances_balances_proto_depIdxs = nil
}
