// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.3
// source: balances/balances.proto

package balancespb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	BalancesService_UpdateBalances_FullMethodName = "/balances.BalancesService/UpdateBalances"
)

// BalancesServiceClient is the client API for BalancesService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type BalancesServiceClient interface {
	UpdateBalances(ctx context.Context, in *UpdateBalancesRequest, opts ...grpc.CallOption) (*UpdateBalancesResponse, error)
}

type balancesServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewBalancesServiceClient(cc grpc.ClientConnInterface) BalancesServiceClient {
	return &balancesServiceClient{cc}
}

func (c *balancesServiceClient) UpdateBalances(ctx context.Context, in *UpdateBalancesRequest, opts ...grpc.CallOption) (*UpdateBalancesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateBalancesResponse)
	err := c.cc.Invoke(ctx, BalancesService_UpdateBalances_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BalancesServiceServer is the server API for BalancesService service.
// All implementations must embed UnimplementedBalancesServiceServer
// for forward compatibility.
type BalancesServiceServer interface {
	UpdateBalances(context.Context, *UpdateBalancesRequest) (*UpdateBalancesResponse, error)
	mustEmbedUnimplementedBalancesServiceServer()
}

// UnimplementedBalancesServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedBalancesServiceServer struct{}

func (UnimplementedBalancesServiceServer) UpdateBalances(context.Context, *UpdateBalancesRequest) (*UpdateBalancesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateBalances not implemented")
}
func (UnimplementedBalancesServiceServer) mustEmbedUnimplementedBalancesServiceServer() {}
func (UnimplementedBalancesServiceServer) testEmbeddedByValue()                         {}

// UnsafeBalancesServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to BalancesServiceServer will
// result in compilation errors.
type UnsafeBalancesServiceServer interface {
	mustEmbedUnimplementedBalancesServiceServer()
}

func RegisterBalancesServiceServer(s grpc.ServiceRegistrar, srv BalancesServiceServer) {
	// If the following call pancis, it indicates UnimplementedBalancesServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&BalancesService_ServiceDesc, srv)
}

func _BalancesService_UpdateBalances_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateBalancesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BalancesServiceServer).UpdateBalances(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BalancesService_UpdateBalances_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BalancesServiceServer).UpdateBalances(ctx, req.(*UpdateBalancesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// BalancesService_ServiceDesc is the grpc.ServiceDesc for BalancesService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var BalancesService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "balances.BalancesService",
	HandlerType: (*BalancesServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "UpdateBalances",
			Handler:    _BalancesService_UpdateBalances_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "balances/balances.proto",
}
